//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesafioPloomes
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        public int idUser { get; set; }
        public string Nome { get; set; }
        public byte[] Senha { get; set; }
        public Nullable<int> idCargo { get; set; }
    
        public virtual tbCargos tbCargos { get; set; }
    }
}
